# Generated by Django 2.2.12 on 2020-06-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
    ]
