# Generated by Django 2.2.12 on 2020-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('key', models.CharField(db_index=True, max_length=50, unique=True)),
                ('value', models.CharField(max_length=25)),
                ('choices', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
