# Generated by Django 2.2.14 on 2020-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0004_auto_20200716_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='choices',
            field=models.CharField(max_length=70, verbose_name='choices'),
        ),
    ]
