# Generated by Django 4.2.5 on 2023-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsettings', '0008_auto_20220905_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
