# Generated by Django 4.2.10 on 2024-02-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appsettings", "0010_auto_20231030_1305"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appsettings",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
