# Generated by Django 2.2.10 on 2020-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=64)),
                ('login', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=14, null=True)),
                ('details', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
