# Generated by Django 2.2.12 on 2020-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
