# Generated by Django 2.2.13 on 2020-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computes', '0002_auto_20200529_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='details',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='hostname',
            field=models.CharField(max_length=64, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='login',
            field=models.CharField(max_length=20, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='compute',
            name='password',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='password'),
        ),
    ]
