# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computes', '0002_compute_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compute',
            name='details',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='compute',
            name='hostname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='compute',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
