# Generated by Django 3.2.15 on 2022-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name='state')),
                ('size', models.IntegerField(verbose_name='size')),
                ('free', models.IntegerField(verbose_name='free')),
                ('status', models.CharField(max_length=128, verbose_name='status')),
                ('path', models.CharField(max_length=128, verbose_name='path')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
                ('autostart', models.BooleanField(verbose_name='autostart')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'No pool name has been entered'}, max_length=20, verbose_name='name')),
                ('status', models.IntegerField(verbose_name='status')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('size', models.IntegerField(verbose_name='size')),
                ('volumes', models.IntegerField(verbose_name='volumes')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('type', models.CharField(choices=[('qcow2', 'qcow2 (recommended)'), ('qcow', 'qcow'), ('raw', 'raw')], max_length=12, verbose_name='format')),
                ('allocation', models.IntegerField(verbose_name='allocation')),
                ('size', models.IntegerField(verbose_name='size')),
            ],
            options={
                'verbose_name_plural': 'Volumes',
                'managed': False,
            },
        ),
    ]
