# Generated by Django 2.2.10 on 2020-01-28 07:01

from django.db import migrations


def add_useradmin(apps, schema_editor):
    from django.utils import timezone
    from django.contrib.auth.models import User
    from accounts.models import UserAttributes

    admin = User.objects.create_superuser('admin', None, 'admin', last_login=timezone.now())
    UserAttributes(user=admin, max_instances=-1, max_cpus=-1, max_memory=-1, max_disk_size=-1).save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_useradmin),
    ]
