# Generated by Django 2.2.12 on 2020-05-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apply_change_password'),
        ('instances', '0003_migrate_can_clone_instances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattributes',
            name='can_clone_instances',
        ),
    ]
