# Generated by Django 2.2.10 on 2020-01-28 07:01
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uuid', models.CharField(max_length=36)),
                ('is_template', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('compute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computes.Compute')),
            ],
        ),
    ]
