# Generated by Django 2.2.13 on 2020-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_auto_20200615_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='uuid',
            field=models.CharField(db_index=True, max_length=36, verbose_name='uuid'),
        ),
    ]
