# Generated by Django 2.2.13 on 2020-06-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0006_addFlavors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='label',
            field=models.CharField(max_length=12, unique=True, verbose_name='label'),
        ),
    ]
