# Generated by Django 2.2.13 on 2020-07-17 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0008_auto_20200708_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionset',
            options={'default_permissions': (), 'managed': False, 'permissions': [('clone_instances', 'Can clone instances'), ('passwordless_console', 'Can access console without password')]},
        ),
    ]
