# Generated by Django 3.2.14 on 2022-07-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0009_auto_20200717_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionset',
            options={'default_permissions': (), 'managed': False, 'permissions': [('clone_instances', 'Can clone instances'), ('passwordless_console', 'Can access console without password'), ('view_instances', 'Can view instances'), ('snapshot_instances', 'Can snapshot instances')]},
        ),
        migrations.AddField(
            model_name='instance',
            name='drbd',
            field=models.CharField(default='None', max_length=24, verbose_name='drbd'),
        ),
    ]
