# Generated by Django 3.2.15 on 2022-08-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0010_auto_20220722_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'required': 'No Virtual Machine name has been entered'}, max_length=64)),
                ('firmware', models.CharField(max_length=50)),
                ('vcpu', models.IntegerField(error_messages={'required': 'No VCPU has been entered'})),
                ('vcpu_mode', models.CharField(blank=True, max_length=20)),
                ('disk', models.IntegerField(blank=True)),
                ('memory', models.IntegerField(error_messages={'required': 'No RAM size has been entered'})),
                ('networks', models.CharField(error_messages={'required': 'No Network pool has been choosen'}, max_length=256)),
                ('nwfilter', models.CharField(blank=True, max_length=256)),
                ('storage', models.CharField(blank=True, max_length=256)),
                ('template', models.CharField(blank=True, max_length=256)),
                ('images', models.CharField(blank=True, max_length=256)),
                ('cache_mode', models.CharField(error_messages={'required': 'Please select HDD cache mode'}, max_length=12)),
                ('hdd_size', models.IntegerField(blank=True)),
                ('meta_prealloc', models.BooleanField(blank=True, default=False)),
                ('virtio', models.BooleanField(default=True)),
                ('qemu_ga', models.BooleanField(default=False)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('console_pass', models.CharField(blank=True, max_length=64)),
                ('graphics', models.CharField(error_messages={'required': 'Please select a graphics type'}, max_length=12)),
                ('video', models.CharField(error_messages={'required': 'Please select a video driver'}, max_length=12)),
                ('listener_addr', models.CharField(choices=[('127.0.0.1', 'Localhost'), ('0.0.0.0', 'All interfaces')], max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MigrateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(verbose_name='Live')),
                ('xml_del', models.BooleanField(default=True, verbose_name='Undefine XML')),
                ('offline', models.BooleanField(verbose_name='Offline')),
                ('autoconverge', models.BooleanField(default=True, verbose_name='Auto Converge')),
                ('compress', models.BooleanField(default=False, verbose_name='Compress')),
                ('postcopy', models.BooleanField(default=False, verbose_name='Post Copy')),
                ('unsafe', models.BooleanField(default=False, verbose_name='Unsafe')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
