# Generated by Django 2.2.10 on 2020-01-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=12)),
                ('memory', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('disk', models.IntegerField()),
            ],
        ),
    ]
