# Generated by Django 2.2.13 on 2020-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_addFlavors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='disk',
            field=models.IntegerField(verbose_name='disk'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='label',
            field=models.CharField(max_length=12, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='memory',
            field=models.IntegerField(verbose_name='memory'),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='vcpu',
            field=models.IntegerField(verbose_name='vcpu'),
        ),
    ]
