# Generated by Django 2.2.13 on 2020-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='instance',
            field=models.CharField(max_length=50, verbose_name='instance'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='message',
            field=models.CharField(max_length=255, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
    ]
